config/routes.rb
Academia::Application.routes.draw do

  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
# devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
    # devise_for :users
    root :to => 'dashboard#index'
    resources :users do
    	collection do
    		post 'search_data'
    	end
    end
    # root :to => '/users/sign_in'
    
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :dob, :first_name, :last_name, :patient_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def new
  	require 'headless'
    require "selenium-webdriver"
    
    head = Headless.new
    head.start
    
    driver = Selenium::WebDriver.for :firefox
    driver.navigate.to "https://cignaforhcp.cigna.com/web/secure/chcp/windowmanager#tab-hcp.pg.patientsearch$1"
    
    username = driver.find_element(:name, 'username')
    username.send_keys "skedia105"

    password = driver.find_element(:name, 'password')
    password.send_keys "Empclaims100"

    element = driver.find_element(:id, 'button1')
    # element.send_keys "Empclaims100" 
    element.submit
    # driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    sleep(3)
    #tab-hcp.pg.patientsearch
    href_search = driver.find_elements(:class,'patients')
    href_search[1].click
    sleep(1)
    member_id = driver.find_element(:name, 'memberDataList[0].memberId')
    member_id.send_keys params[:user][:patient_id]

    dob = driver.find_element(:name, 'memberDataList[0].dobDate')
    dob.send_keys params[:user][:dob]

    first_name = driver.find_element(:name, 'memberDataList[0].firstName')
    first_name.send_keys params[:user][:first_name]

    last_name = driver.find_element(:name, 'memberDataList[0].lastName')
    last_name.send_keys params[:user][:last_name]
    

    ee = driver.find_elements(:class,'btn-submit-form-patient-search')[0]
    ee.submit

    sleep(3)
    link = driver.find_elements(:class,'oep-managed-link')[5]
    link.click
    sleep(3)
    # puts driver.title
    tables = driver.find_elements(:class,'collapseTable')
    @table1 = tables[0].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table2 = tables[1].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table3 = tables[2].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table4 = tables[3].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table5 = tables[4].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table6 = tables[5].attribute('innerHTML').gsub("\t","").gsub("\n","")

    driver.quit 
    head.destroy

  end

  def index
  end
end

# $("<img>").attr({'id':'img1','style':'margin-top:6%;','src':'http://loadinggif.com/images/image-selection/32.gif'}).appendTo('#innersec');

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def search_data
  	require "selenium-webdriver"
    # head = Headless.new
    # head.start
    
    driver = Selenium::WebDriver.for :phantomjs, :args => ['--ignore-ssl-errors=true']
    # driver = Selenium::WebDriver.for :firefox
    driver.navigate.to "https://cignaforhcp.cigna.com/web/secure/chcp/windowmanager#tab-hcp.pg.patientsearch$1"
    
    username = driver.find_element(:name, 'username')
    username.send_keys "skedia105"

    password = driver.find_element(:name, 'password')
    password.send_keys "Empclaims100"

    element = driver.find_element(:id, 'button1')
    element.send_keys "Empclaims100" 
    element.submit
    # driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    wait = Selenium::WebDriver::Wait.new(:timeout => 10)
    
    sleep(3)
    href_search = driver.find_elements(:class,'patients')
    href_search[1].click
    
    
    sleep(1)  
    member_id = driver.find_element(:name, 'memberDataList[0].memberId')
    member_id.send_keys "102216035"
    dob = driver.find_element(:name, 'memberDataList[0].dobDate')
    dob.send_keys "1/9/1957"
    first_name = driver.find_element(:name, 'memberDataList[0].firstName')
    first_name.send_keys "DEVIKA"
    last_name = driver.find_element(:name, 'memberDataList[0].lastName')
    last_name.send_keys "SHAH"
    ee = driver.find_elements(:class,'btn-submit-form-patient-search')[0]
    ee.submit

    sleep(1)
    link = driver.find_elements(:class,'oep-managed-link')[5]
    link.click
    

    # puts driver.title
    sleep(2)
    tables = driver.find_elements(:class,'collapseTable')
    @table1 = tables[0].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table2 = tables[1].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table3 = tables[2].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table4 = tables[3].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table5 = tables[4].attribute('innerHTML').gsub("\t","").gsub("\n","")
    @table6 = tables[5].attribute('innerHTML').gsub("\t","").gsub("\n","")

    driver.quit 
    # head.destroy
    # redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/batch_courses_helper.rb
module BatchCoursesHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exam_details_helper.rb
module ExamDetailsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/profits_helper.rb
module ProfitsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div class="well signup-form">
	<h3 style="text-align: center;">Patient Search</h3>
	<%= form_for User.new,:url=>search_data_users_path,:html => { :class => 'form-horizontal' } do |f| %>
	  <div class="form-group">
	   	<%= f.label :first_name, :class => 'control-label' %>
		 	<%= f.text_field :first_name, :class =>'form-control' %>
	  </div>
	  <div class="form-group">
	  	<%= f.label :last_name, :class => 'control-label' %>
	 		<%= f.text_field :last_name, :class =>'form-control' %>
	  </div>

	  <div class="form-group">
	  	<%= f.label :patient_id, :class => 'control-label' %>
	 		<%= f.text_field :patient_id, :class =>'form-control' %>
	  </div>

	  <div class="form-group">
	  	<%= f.label :dob, :class => 'control-label' %>
	 		<%= f.text_field :dob, :class =>'form-control datepicker' %>
	  </div>
	  
	  <%= submit_tag "", :value => "► save", :class => "pull-right btn btn-sm btn-primary" %>
	<% end %>
</div>

<style type="text/css">
	.signup-form {
		width: 50%;
		margin: 120px auto 0;
		padding: 20px 50px 20px;
		overflow: hidden;
	}

</style>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <%# @direction = (rtl?) ? 'rtl/' : '' %>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
    <title><%= "Scrapping" %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag 'application', media: 'all'%>
    
  </head>

  <body>
    <div id="content_wrapper" >
      <div id="content"> <%= yield %> </div>
    </div>
  </body>
</html>

app/views/users/search_data.html.erb
<div class="well">
	<div class="panel panel-primary">
		<div class="panel-heading">
			PATIENT AND PLAN DETAIL
		</div>
		<div class="panel-body">
			<table class="table table-striped">
				<%= @table1.html_safe %>
			</table>		
		</div>
	</div>
	

	<div class="panel panel-primary">
		<div class="panel-heading">
			COLLABORATIVE ACCOUNTABLE CARE INFORMATION
		</div>
		<div class="panel-body">
			<table class="table table-striped">
				<%= @table2.html_safe %>
			</table>		
		</div>
	</div>

	<div class="panel panel-primary">
		<div class="panel-heading">
			NOTIFICATION AND REFERRAL
		</div>
		<div class="panel-body">
			<table class="table table-striped">
				<%= @table3.html_safe %>
			</table>		
		</div>
	</div>

	<div class="panel panel-primary">
		<div class="panel-heading">
			HEALTH AND WELLNESS PROGRAMS	
		</div>
		<div class="panel-body">
			<table class="table table-striped">
				<%= @table4.html_safe %>
			</table>		
		</div>
	</div>

	<div class="panel panel-primary">
		<div class="panel-heading">
			MATERNITY	
		</div>
		<div class="panel-body">
			<table class="table table-striped">
				<%= @table5.html_safe %>
			</table>		
		</div>
	</div>

	<div class="panel panel-primary">
		<div class="panel-heading">
			PRESCRIPTION COVERAGE	
		</div>
		<div class="panel-body">
			<table class="table table-striped">
				<%= @table6.html_safe %>
			</table>		
		</div>
	</div>
</div>